.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. mitcoin_qt test_mitcoin_qt
clean: FORCE
	$(MAKE) -C .. mitcoin_qt_clean test_mitcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_mitcoin_qt_check
mitcoin-qt mitcoin-qt.exe: FORCE
	 $(MAKE) -C .. mitcoin_qt
